language: go
dist: trusty
sudo: required
install: true
go:
  - 1.7.1
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.7.1
before_install:
  - sleep 15
  - sudo apt-get install -y
  - sudo apt-get install -y curl
  - mkdir -p $HOME/gopath/bin
  - mkdir -p $HOME/gopath/src/github/openebs
  - cd $HOME/gopath/src/github/openebs && git clone https://github.com/openebs/jiva.git
script:
  - cd $HOME/gopath/src/github/openebs/jiva && make build
